env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git
    MANIFEST_BRANCH: arrow-12.1
    DEVICE: garden
    OEM: xiaomi
    DT_LINK: https://github.com/adarsh756/android_device_xiaomi_garden.git -b arrowos
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/Yukina-Supremacy/android_vendor_xiaomi_garden.git -b twelve30
    VT_PATH: vendor/$OEM/$DEVICE
    EXTRA_CMD: "git clone --depth=1 https://github.com/ghostrider-reborn/prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-6.x.git $SYNC_PATH/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-6.x"
    LUNCH_COMBO: arrow_garden-userdebug
    TARGET: bacon
    OUTPUT: ArrowOS*.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  timeout_in: 240m
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
      - export DEBIAN_FRONTEND=noninteractive
      - apt update
      - apt install sudo
      - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
      - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
      - apt-get install -y tzdata
      - dpkg-reconfigure --frontend noninteractive tzdata
      - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y
      - sudo apt install python3 -y
      - sudo ln -sf /usr/bin/python3 /usr/bin/python
      - git config --global user.name "Sushrut1101"
      - git config --global user.email "guptasushrut@gmail.com"
      - git clone https://github.com/akhilnarang/scripts.git ~/scripts
      - cd ~/scripts
      - sudo bash setup/android_build_env.sh
      - cd ~
  
  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
